name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-test
    steps:
      - uses: actions/checkout@v2

      - name: Diff files
        run: |
          git fetch origin ${{ env.GITHUB_BASE_REF }}:${{ env.GITHUB_BASE_REF }}
          git fetch origin ${{ env.GITHUB_HEAD_REF }}:${{ env.GITHUB_HEAD_REF }}
          git checkout ${{ env.GITHUB_HEAD_REF }}
          echo $(git diff --name-only ${{ env.GITHUB_BASE_REF }}..${{ env.GITHUB_HEAD_REF }})
