name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Diff files
        run: |
          echo "test echo $GITHUB_BASE_REF:$GITHUB_BASE_REF"
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF
          git fetch origin $GITHUB_HEAD_REF:$GITHUB_HEAD_REF
          git checkout $GITHUB_HEAD_REF
          DIFF=$(git diff --name-only $GITHUB_BASE_REF..$GITHUB_HEAD_REF)
          echo "$DIFF"
